### ISSUE TITLE
missing error messages from stderr

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [danielzzz/node-ping#158]
### 👟 Reproduction steps

Ping something which returns errors.

### Expected behavior

Messages from stderr are included in the responses.
### Actual Behavior

The responses don't have messages from stderr included.

Relevant issue: louislam/uptime-kuma#2896

**Comment by mondwan** [comment]
Hello, errors reported here are too generic. Please include how you run the library, actual responses, and expected responses.

As mentioned in louislam/uptime-kuma/issues/2896, please also include how your system behaved while running the system ping if you believed the errors are coming from the system instead.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
I updated the thread with outputs. We can know that `outputs` is empty if there is nothing in stdout. We should also include stderr for more info for debugging issues.

**Comment by mondwan** [comment]
Hopefully, #159 should resolve this bug

**Comment by mondwan** [comment]
Try release 0.4.4

**Comment by wonderfulShrineMaidenOfParadise** [comment]
```
{
  inputHost: 'p.p',
  host: 'unknown',
  alive: false,
  output: '',
  time: 'unknown',
  times: [],
  min: 'unknown',
  max: 'unknown',
  avg: 'unknown',
  stddev: 'unknown',
  packetLoss: 'unknown'
}
{
  inputHost: '1.1.1.1',
  host: '1.1.1.1',
  alive: true,
  output: 'PING 1.1.1.1 (1.1.1.1): 56 data bytes\n' +
    '64 bytes from 1.1.1.1: seq=0 ttl=42 time=13.661 ms\n' +
    '\n' +
    '--- 1.1.1.1 ping statistics ---\n' +
    '1 packets transmitted, 1 packets received, 0% packet loss\n' +
    'round-trip min/avg/max = 13.661/13.661/13.661 ms\n',
  time: 13.661,
  times: [ 13.661 ],
  min: 'unknown',
  max: 'unknown',
  avg: 'unknown',
  stddev: 'NaN',
  packetLoss: '0.000',
  numeric_host: '1.1.1.1)'
}
```

I can see some errors now, but it still doesn't show anything when pinging `p.p`, a url provided by privoxy.

The error is `ping: p.p: Name does not resolve` or `ping: bad address 'p.p'`.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
```
{
  inputHost: 'p.p',
  host: 'bad',
  alive: false,
  output: "ping: bad address 'p.p'\n",
  time: 'unknown',
  times: [],
  min: 'unknown',
  max: 'unknown',
  avg: 'unknown',
  stddev: 'unknown',
  packetLoss: 'unknown',
  numeric_host: 'ddres'
}
{
  inputHost: '1.1.1.1',
  host: '1.1.1.1',
  alive: false,
  output: 'PING 1.1.1.1 (1.1.1.1): 56 data bytes\n' +
    'ping: permission denied (are you root?)\n',
  time: 'unknown',
  times: [],
  min: 'unknown',
  max: 'unknown',
  avg: 'unknown',
  stddev: 'unknown',
  packetLoss: 'unknown',
  numeric_host: '1.1.1.1)'
}
```

Thank you for fixing!

**Comment by mondwan** [comment]
That's great.

Just wondering. Hopefully, you are using BusyBox or something like that.
Can you also show me the value of "os.platform()"?

The value in the numeric host field is bad. But, it is probably due to
picking a wrong parser. The library should pick a Mac base parser for your
case

**Comment by wonderfulShrineMaidenOfParadise** [comment]
> Can you also show me the value of "os.platform()"?

`linux`. I don't really understand. Do you need to know something specific?

**Comment by mondwan** [comment]
I mean I would like to know the value from the module in node js `os.platform()`.

In your captured sample, the value of the field `numeric_host` is `1.1.1.1)`, the ending bracket is something unexpected. Hopefully, this problematic output is due to the bad parser being selected.

Given that the format of ping's output depends on the underlying platform, there are 3 kinds of parsers in this library: MAC / LINUX / WINDOW. This library will pick the corresponding parser depends on the value from `os.platform()`.

* FYI, https://github.com/danielzzz/node-ping/blob/v0.4.4/lib/ping-promise.js#L37

The problematic `numeric_host` value can be resolved as long as a MAC based parser being picked. That's why I would like to know the value of `os.platform()` for your underlying system. Then, I can fix the factory accordingly.

* FYI, https://github.com/danielzzz/node-ping/blob/v0.4.4/lib/builder/factory.js#L32

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Yes it returns `linux` and it seems to be correct.
